# basic options
title: Vakantie september 2021 Nijmegen en Snikzwaag
author: Kees
description: Blog van de najaarsvakantie naar Nijmegen en Snikzwaag

# URL to GitHub repo
baseurl: "/2021-09-nijmegen-en-snikzwaag" 
url: "https://prudento-nl.github.io" 

# URL to images folder at GitHub repo LET OP het format van de link met de PUNT!
images: "https://prudento-nl.github.io/2021-09-nijmegen-en-snikzwaag/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
